# Generated by Django 4.2.3 on 2023-08-04 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
